### ISSUE TITLE
Build/Publish action on master fails on GitHub packages push

### ISSUE THREAD

**Issue by Vaerian** [Cumulus-Mods/Art-of-Alchemy#3]
The GitHub action inherited from the old repository includes outdated information relating to GitHub packages meaning it fails every time regardless of whether or not the code builds or not. This should be a quick fix that can likely skip the PR process as it's just administrative to the repository itself. I'll let @Sturmlilie determine which specific implementation is most fitting.

**Comment by Sturmlilie** [comment]
I'd love to take care of this, but to be honest, I have not the slightest clue how Github actions work.. do you think you could just turn it all off for the time being?

**Comment by Sturmlilie** [comment]
Okay, I've disabled the publishing step for now.
